
package main.java.pack;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UniversityService", targetNamespace = "http://pack/", wsdlLocation = "http://localhost:8080/SoaProject-ejb/UniversityService?wsdl")
public class UniversityService_Service
    extends Service
{

    private final static URL UNIVERSITYSERVICE_WSDL_LOCATION;
    private final static WebServiceException UNIVERSITYSERVICE_EXCEPTION;
    private final static QName UNIVERSITYSERVICE_QNAME = new QName("http://pack/", "UniversityService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SoaProject-ejb/UniversityService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UNIVERSITYSERVICE_WSDL_LOCATION = url;
        UNIVERSITYSERVICE_EXCEPTION = e;
    }

    public UniversityService_Service() {
        super(__getWsdlLocation(), UNIVERSITYSERVICE_QNAME);
    }

    public UniversityService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), UNIVERSITYSERVICE_QNAME, features);
    }

    public UniversityService_Service(URL wsdlLocation) {
        super(wsdlLocation, UNIVERSITYSERVICE_QNAME);
    }

    public UniversityService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UNIVERSITYSERVICE_QNAME, features);
    }

    public UniversityService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UniversityService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UniversityService
     */
    @WebEndpoint(name = "UniversityServicePort")
    public UniversityService getUniversityServicePort() {
        return super.getPort(new QName("http://pack/", "UniversityServicePort"), UniversityService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UniversityService
     */
    @WebEndpoint(name = "UniversityServicePort")
    public UniversityService getUniversityServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://pack/", "UniversityServicePort"), UniversityService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UNIVERSITYSERVICE_EXCEPTION!= null) {
            throw UNIVERSITYSERVICE_EXCEPTION;
        }
        return UNIVERSITYSERVICE_WSDL_LOCATION;
    }

}
