
package main.java.pack_no_auth;


import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UniversityNoAuthorizationService", targetNamespace = "http://pack/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UniversityNoAuthorizationService {


    /**
     * 
     * @param surname
     * @param name
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     */
    @WebMethod(action = "get_avatar")
    @WebResult(name = "encoded_image", targetNamespace = "")
    @RequestWrapper(localName = "getStudentAvatar", targetNamespace = "http://pack/", className = "main.java.pack_no_auth.GetStudentAvatar")
    @ResponseWrapper(localName = "getStudentAvatarResponse", targetNamespace = "http://pack/", className = "main.java.pack_no_auth.GetStudentAvatarResponse")
    public String getStudentAvatar(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "surname", targetNamespace = "")
        String surname)
        throws IOException_Exception
    ;

}
