
package main.java.pack_no_auth;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UniversityNoAuthorizationService", targetNamespace = "http://pack/", wsdlLocation = "http://localhost:8080/SoaProject-ejb/UniversityNoAuthorizationService?wsdl")
public class UniversityNoAuthorizationService_Service
    extends Service
{

    private final static URL UNIVERSITYNOAUTHORIZATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException UNIVERSITYNOAUTHORIZATIONSERVICE_EXCEPTION;
    private final static QName UNIVERSITYNOAUTHORIZATIONSERVICE_QNAME = new QName("http://pack/", "UniversityNoAuthorizationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SoaProject-ejb/UniversityNoAuthorizationService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UNIVERSITYNOAUTHORIZATIONSERVICE_WSDL_LOCATION = url;
        UNIVERSITYNOAUTHORIZATIONSERVICE_EXCEPTION = e;
    }

    public UniversityNoAuthorizationService_Service() {
        super(__getWsdlLocation(), UNIVERSITYNOAUTHORIZATIONSERVICE_QNAME);
    }

    public UniversityNoAuthorizationService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), UNIVERSITYNOAUTHORIZATIONSERVICE_QNAME, features);
    }

    public UniversityNoAuthorizationService_Service(URL wsdlLocation) {
        super(wsdlLocation, UNIVERSITYNOAUTHORIZATIONSERVICE_QNAME);
    }

    public UniversityNoAuthorizationService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UNIVERSITYNOAUTHORIZATIONSERVICE_QNAME, features);
    }

    public UniversityNoAuthorizationService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UniversityNoAuthorizationService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UniversityNoAuthorizationService
     */
    @WebEndpoint(name = "UniversityNoAuthorizationServicePort")
    public UniversityNoAuthorizationService getUniversityNoAuthorizationServicePort() {
        return super.getPort(new QName("http://pack/", "UniversityNoAuthorizationServicePort"), UniversityNoAuthorizationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UniversityNoAuthorizationService
     */
    @WebEndpoint(name = "UniversityNoAuthorizationServicePort")
    public UniversityNoAuthorizationService getUniversityNoAuthorizationServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://pack/", "UniversityNoAuthorizationServicePort"), UniversityNoAuthorizationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UNIVERSITYNOAUTHORIZATIONSERVICE_EXCEPTION!= null) {
            throw UNIVERSITYNOAUTHORIZATIONSERVICE_EXCEPTION;
        }
        return UNIVERSITYNOAUTHORIZATIONSERVICE_WSDL_LOCATION;
    }

}
